import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import DataStore from '@/app/datastore/dataprovider'
import { Toaster } from '@/components/ui/toaster'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Academics ',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <DataStore>
        {children}
        
        </DataStore>
        </body>
    </html>
  )
}
