'use client'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import DataStore from '@/app/datastore/dataprovider'
import { Toaster } from '@/components/ui/toaster'
import AuthProvider from '@/components/authprovider'
import { usePathname} from 'next/navigation' 
import Headers  from '@/components/menubar'

const inter = Inter({ subsets: ['latin'] })

// export const metadata: Metadata = {
//   title: 'Academics ',
//   description: 'Generated by create next app',
// }

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) 


{
  const pathname = usePathname()
  const showHeader = pathname === '/auth/signIn' || pathname === '/auth/signOut' ? false : true;
  return (
    <html lang="en">
      <body className={inter.className}>
      {showHeader && <Headers />}
        <DataStore>
          <AuthProvider>
        {children}
        </AuthProvider>
        </DataStore>
        </body>
    </html>
  )
}
